"""added deleted_at column

Revision ID: b34fdac221f8
Revises: 1710c4ce6ba8
Create Date: 2025-08-17 19:24:21.457067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b34fdac221f8"
down_revision: Union[str, Sequence[str], None] = "1710c4ce6ba8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    # ### end Alembic commands ###
